BOT_TOKEN = "1921126348:AAH1jpznNf7E_PyeiVvHd7x8g_I4V-CQ5XY"
ETHERSCAN_TOKEN = "USBQMF21HH7VYQXVP2ITUMHM8XAWVHVWAA"

DB_FILE = "bot.db"

ADD_WALLET = "new"
ALL_WALLET = "all"
CHECK_BALANCE = "balance"
DELETE_WALLET_BY_ID = "delete_by_id"

MIN_DURATION_BTW_REQUESTS = 1.0 # unit: second
